

# 신경망 모형

In [2]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [3]:
(1.1*1.8*0.95)**(1/3)

1.2344199497598127

In [25]:
from scipy import stats
import numpy as np 

mu = 15.5
var = 3.2
n = 20 # 임의의 수 입력
print('신뢰구간:', stats.t.interval(alpha=0.9, loc=15.5, scale=np.sqrt(var/n), df=(n-1)))


신뢰구간: (14.808346875391452, 16.191653124608546)


/tmp/ipykernel_10669/2134426337.py:7: DeprecationWarning: Use of keyword argument `alpha` for method `interval` is deprecated. Use first positional argument or keyword argument `confidence` instead.
  print('신뢰구간:', stats.t.interval(alpha=0.9, loc=15.5, scale=np.sqrt(var/n), df=(n-1)))


In [26]:
import statsmodels

In [27]:

help(statsmodels)

Help on package statsmodels:

NAME
    statsmodels

PACKAGE CONTENTS
    _version
    api
    base (package)
    compat (package)
    conftest
    datasets (package)
    discrete (package)
    distributions (package)
    duration (package)
    emplike (package)
    formula (package)
    gam (package)
    genmod (package)
    graphics (package)
    imputation (package)
    interface (package)
    iolib (package)
    miscmodels (package)
    multivariate (package)
    nonparametric (package)
    othermod (package)
    regression (package)
    robust (package)
    sandbox (package)
    src (package)
    stats (package)
    tests (package)
    tools (package)
    tsa (package)

FUNCTIONS
    test(extra_args=None, exit=False)
        Run the test suite
        
        Parameters
        ----------
        extra_args : list[str]
            List of argument to pass to pytest when running the test suite. The
            default is ['--tb=short', '--disable-pytest-warnings'].
        exit : b

In [31]:
statsmodels.api

AttributeError: module 'statsmodels' has no attribute 'api'

In [30]:
help(statsmodels)

Help on function test in module statsmodels:

test(extra_args=None, exit=False)
    Run the test suite
    
    Parameters
    ----------
    extra_args : list[str]
        List of argument to pass to pytest when running the test suite. The
        default is ['--tb=short', '--disable-pytest-warnings'].
    exit : bool
        Flag indicating whether the test runner should exist when finished.
    
    Returns
    -------
    int
        The status code from the test run if exit is False.



In [ ]:
from scipy.stats.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_iris

iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.DataFrame(iris.target, columns=['target'])

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=1)

In [32]:
clf = MLPClassifier(hidden_layer_sizes=(100,10), solver='lbfgs', alpha=100, random_state=1)  # 히든레이어와 알파값을 조정하며 분류, 알파값이 작을수록 복잡도 상승
clf.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(activation='relu', alpha=100, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100, 10), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [33]:
pred = clf.predict(X_test)
pred_proba = clf.predict_proba(X_test)

In [34]:
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[ 0  0 14]
 [ 0  0 18]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           1       0.00      0.00      0.00        18
           2       0.29      1.00      0.45        13

    accuracy                           0.29        45
   macro avg       0.10      0.33      0.15        45
weighted avg       0.08      0.29      0.13        45



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# SVM  - 마진을 최대로 하는 초평면을 결정하는 모델, C 로 에러 허용

# SVM with Kernel - 선형관계가 아닌경우 사용

- 장점 :예측의 정확도가 높음
- 단점 : C를 결정해야함, 모형 구축에 시간이 오래걸림

In [35]:
from sklearn import svm

In [ ]:
iris=load_iris()
X=iris.data[:,:2]
y=iris.target

# C가 클수록 error를 적게 허용하는것
# C가 무한대이면, 오분류가 하나도 없는 SVM상황이 될 것
C=1
clf=svm.SVC(kernel='linear',C=C) # kernel='linear'는 커널을 안주는 모형
clf.fit(X,y)

## kernel SVM 적합 및 비교

In [ ]:
# LinearSVC - 위 모형과 비슷하지만 결과가 다르게 나옴 -> 사용한 알고리즘이 달라서, loss funtion이 달라서
clf=svm.LinearSVC(C=C,max_iter=10000)
clf.fit(X,y)
y_pred=clf.predict(X)
confusion_matrix(y,y_pred)

In [ ]:
# radial basis function
clf=svm.SVC(kernel='rbf',gamma=0.7,C=C,max_iter=10000)
clf.fit(X,y)
y_pred=clf.predict(X)
confusion_matrix(y,y_pred)

In [ ]:
# polynomial kernel
clf=svm.SVC(kernel='poly',degree=3,C=C,gamma='auto')
clf.fit(X,y)
y_pred=clf.predict(X)
confusion_matrix(y,y_pred)

# LDA

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
y = np.array([1, 1, 1, 2, 2, 2])

clf=LinearDiscriminantAnalysis()
clf.fit(X,y)

print(clf.predict([[-0.8, -1]]))