In [1]:

# implement logistic regression in Pytorch

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


/home/tekim/haha/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
torch.manual_seed(1)

In [3]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [4]:
x_train

tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])

In [6]:
model = nn.Sequential(
    nn.Linear(2,1),
    nn.Sigmoid()
)


In [7]:
model(x_train)

tensor([[0.4020],
        [0.4147],
        [0.6556],
        [0.5948],
        [0.6788],
        [0.8061]], grad_fn=<SigmoidBackward0>)

In [8]:


# optimizer 
optimizer = optim.SGD(model.parameters(), lr = 1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산

    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs,cost.item()
        ))

Epoch    0/1000 Cost: 0.539713
Epoch  100/1000 Cost: 0.134272
Epoch  200/1000 Cost: 0.080486
Epoch  300/1000 Cost: 0.057820
Epoch  400/1000 Cost: 0.045251
Epoch  500/1000 Cost: 0.037228
Epoch  600/1000 Cost: 0.031649
Epoch  700/1000 Cost: 0.027538
Epoch  800/1000 Cost: 0.024381
Epoch  900/1000 Cost: 0.021877
Epoch 1000/1000 Cost: 0.019843


In [11]:
hypothesis = model(x_train)
print(hypothesis)

tensor([[2.7616e-04],
        [3.1595e-02],
        [3.8959e-02],
        [9.5624e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)


In [12]:
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)

tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])
