In [1]:
import torch

/home/tekim/haha/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
t = torch.FloatTensor([0,1])
print(t.shape)
print(t.dim())
print(t.size())

torch.Size([2])
1
torch.Size([2])


In [33]:
t = torch.FloatTensor([[[1., 3., 2.],
                       [4., 5., 6.]],
                       [[7., 9., 8.],
                       [10., 11., 12.]
                      ]])
print(t)

tensor([[[ 1.,  3.,  2.],
         [ 4.,  5.,  6.]],

        [[ 7.,  9.,  8.],
         [10., 11., 12.]]])


In [34]:

print(t.dim())
print(t.shape)


3
torch.Size([2, 2, 3])


In [35]:
t[1,1,2]

tensor(12.)

In [36]:
t.max(dim=0)
t.max(dim=1)
t.max(dim=2)

torch.return_types.max(
values=tensor([[ 3.,  6.],
        [ 9., 12.]]),
indices=tensor([[1, 2],
        [1, 2]]))

In [10]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [16]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2 ]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [17]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [18]:
t = m1 + m2

t.argmax()

tensor(3)

In [38]:
import numpy as np

In [39]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [43]:
ft.shape

torch.Size([2, 2, 3])

In [44]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [45]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [46]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)

print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [48]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [51]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [52]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [53]:
print(lt.float())
print(lt)

tensor([1., 2., 3., 4.])
tensor([1, 2, 3, 4])


In [54]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [55]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [56]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [57]:
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [58]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [60]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z]).shape)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])


In [61]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [63]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [64]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [66]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [67]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [68]:
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[0., 2., 4.],
        [4., 2., 0.]])
tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [69]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[0., 2., 4.],
        [4., 2., 0.]])
tensor([[0., 2., 4.],
        [4., 2., 0.]])
