In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
# model = nn.Linear(input_dim, putput_dim)
# cost = F.mse_loss(prediction, y_train)

NameError: name 'input_dim' is not defined

In [4]:
torch.manual_seed(1)

In [16]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [17]:
model = nn.Linear(1,1)

In [18]:
print((model.parameters()))
print(list(model.parameters()))

<generator object Module.parameters at 0x7f2d909e56d0>
[Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]


In [19]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [24]:
nb_epochs = 2000

for epoch in range(nb_epochs+1):

    prediction = model(x_train)

    cost = F.mse_loss(prediction,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))


Epoch    0/2000 Cost: 0.000000
Epoch  100/2000 Cost: 0.000000
Epoch  200/2000 Cost: 0.000000
Epoch  300/2000 Cost: 0.000000
Epoch  400/2000 Cost: 0.000000
Epoch  500/2000 Cost: 0.000000
Epoch  600/2000 Cost: 0.000000
Epoch  700/2000 Cost: 0.000000
Epoch  800/2000 Cost: 0.000000
Epoch  900/2000 Cost: 0.000000
Epoch 1000/2000 Cost: 0.000000
Epoch 1100/2000 Cost: 0.000000
Epoch 1200/2000 Cost: 0.000000
Epoch 1300/2000 Cost: 0.000000
Epoch 1400/2000 Cost: 0.000000
Epoch 1500/2000 Cost: 0.000000
Epoch 1600/2000 Cost: 0.000000
Epoch 1700/2000 Cost: 0.000000
Epoch 1800/2000 Cost: 0.000000
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [25]:
# 임의의 입력 4를 선언
new_var =  torch.FloatTensor([[4.0]]) 
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y) 

훈련 후 입력이 4일 때의 예측값 : tensor([[8.0000]], grad_fn=<AddmmBackward0>)


In [26]:
print(list(model.parameters()))

[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([8.7017e-06], requires_grad=True)]


In [41]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [42]:
torch.manual_seed(1)

In [43]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [44]:
W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [45]:
model = nn.Linear(3,1)

In [46]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [47]:
optimizer = optim.SGD(model.parameters(), lr = 1e-5)


In [48]:
nb_epochs = 2000
for epoch in range(nb_epochs + 1):
    prediction = model(x_train)

    cost = F.mse_loss(prediction,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f'epoch : {epoch} / {nb_epochs} , Cost : {cost.squeeze():.6f}')

        

epoch : 0 / 2000 , Cost : 31667.597656
epoch : 100 / 2000 , Cost : 0.225988
epoch : 200 / 2000 , Cost : 0.223910
epoch : 300 / 2000 , Cost : 0.221930
epoch : 400 / 2000 , Cost : 0.220059
epoch : 500 / 2000 , Cost : 0.218270
epoch : 600 / 2000 , Cost : 0.216571
epoch : 700 / 2000 , Cost : 0.214955
epoch : 800 / 2000 , Cost : 0.213413
epoch : 900 / 2000 , Cost : 0.211949
epoch : 1000 / 2000 , Cost : 0.210558
epoch : 1100 / 2000 , Cost : 0.209237
epoch : 1200 / 2000 , Cost : 0.207971
epoch : 1300 / 2000 , Cost : 0.206764
epoch : 1400 / 2000 , Cost : 0.205616
epoch : 1500 / 2000 , Cost : 0.204527
epoch : 1600 / 2000 , Cost : 0.203479
epoch : 1700 / 2000 , Cost : 0.202487
epoch : 1800 / 2000 , Cost : 0.201542
epoch : 1900 / 2000 , Cost : 0.200638
epoch : 2000 / 2000 , Cost : 0.199769


In [49]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.2305]], grad_fn=<AddmmBackward0>)
