In [1]:
import torch
import numpy as np

/home/tekim/haha/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [4]:
torch.manual_seed(1)

In [5]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [6]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [7]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [8]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True) 
# 가중치 W를 출력
print(W) 

tensor([0.], requires_grad=True)


In [9]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [10]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [11]:
cost = torch.mean((hypothesis - y_train) **2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [12]:
optimizer = optim.SGD([W,b], lr=0.01)

In [14]:
optimizer.zero_grad()

cost.backward()

optimizer.step()

In [40]:
nb_epochs = 2000

for i in range(nb_epochs):
    hypothesis = x_train * W + b

    cost = torch.mean((hypothesis - y_train) **2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()


    if i % 100 == 0:
        print("Epoch {:4d}/{} W: {:6.3f}, b : {:.3f} Cost: {:.6f}".format(
            i,nb_epochs,W.item(),b.item(),cost.item()
        ))

Epoch    0/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch  100/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch  200/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch  300/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch  400/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch  500/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch  600/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch  700/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch  800/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch  900/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch 1000/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch 1100/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch 1200/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch 1300/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch 1400/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch 1500/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch 1600/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch 1700/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch 1800/2000 W:  2.000, b : 0.000 Cost: 0.000000
Epoch 1900/2